name: Deploy Laravel 

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Build with Laravel
      run: |
        composer install
        npm install
        npm run prod
        php artisan config:cache

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        name: pages
        path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: pages
        path: public

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public