name: Deploy Laravel

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  composer:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: composer update

    - name: Archive vendor folder
      run: tar czf vendor.tar.gz vendor

    - name: Upload artifact
      uses: actions/upload-artifact@v2  
      with:
        name: vendor
        path: vendor.tar.gz

  build:

    needs: composer

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Download vendor
      uses: actions/download-artifact@v2
      with:
        name: vendor
        path: .

    - name: Unzip vendor
      run: tar xzf vendor.tar.gz

    - name: Build Assets  
      run: |
        npm install
        npm run prod

    - name: Cache configuration
      run: php artisan config:cache

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pages
        path: public
  
  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - name: Download artifact  
      uses: actions/download-artifact@v2
      with:
       name: pages
       path: public

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public